plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.advantech.oemconfigtest'
    compileSdk 34

    buildFeatures {
        viewBinding true
    }

    defaultConfig {
        applicationId "com.advantech.oemconfigtest"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.1"

    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "${rootProject.name}_v${defaultConfig.versionName}_${variant.buildType.name}.apk"
        }
    }

    signingConfigs {
        common {
            keyAlias 'android'
            keyPassword 'android'
            storePassword 'android'
            storeFile file('../platform.jks')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.common
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.androidx.preference
}